name: Build, Test, and Push to ECR

on:
  push:
    branches:
      - develop  # Or your specific branch

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Set up Python 3.10

    - name: Install Poetry
      run: |
        pip install --upgrade pip
        pip install poetry

    - name: Install dependencies using Poetry
      run: |
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi

    - name: Run unit tests
      run: |
        poetry run python -m unittest ./api/test_app.py

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: latest  # Change this as necessary
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
