name: Build and Push to ECR

on:
  push:
    branches:
      - main
      - develop  # Set your default branch here    

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/develop' && 'dd') || (github.ref == 'refs/heads/main' && 'prod') }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{secrets.AWS_REGION}}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        BRANCH_NAME: ${{ github.ref_name }}
        COMMIT_SHA: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$COMMIT_SHA \
                    --build-arg REDIS_HOST=${{ secrets.REDIS_HOST }} \
                    --build-arg REDIS_PWD=${{ secrets.REDIS_PWD }} \
                    --build-arg GIT_TOKEN=${{ secrets.GIT_TOKEN }} \
                    --build-arg CONTENT_SOURCE_URL=${{ secrets.OBSIDIAN_REPO }} \
                    .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$COMMIT_SHA
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$COMMIT_SHA $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_NAME
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_NAME